### ISSUE TITLE
flannel start up failed

### ISSUE THREAD

**Issue by gp0014** [coreos/flannel#1157]
I am using flannel as the docker overlay network, but on my one node, when I start up the flannel, it failed with following error:

```
Jul 10 07:29:24 root flanneld-start[2868]: I0710 07:29:24.778932    2868 main.go:475] Determining IP address of default interface
Jul 10 07:29:24 root flanneld-start[2868]: I0710 07:29:24.779184    2868 main.go:488] Using interface with name enp1s0 and address 192.168.199.222
Jul 10 07:29:24 root flanneld-start[2868]: I0710 07:29:24.779193    2868 main.go:505] Defaulting external address to interface address (192.168.199.222)
Jul 10 07:29:24 root flanneld-start[2868]: I0710 07:29:24.779250    2868 main.go:235] Created subnet manager: Etcd Local Manager with Previous Subnet: None
Jul 10 07:29:24 root flanneld-start[2868]: I0710 07:29:24.779255    2868 main.go:238] Installing signal handlers
Jul 10 07:29:24 root flanneld-start[2868]: fatal error: unexpected signal during runtime execution
Jul 10 07:29:24 root flanneld-start[2868]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x63 pc=0x7fd8324b8448]
Jul 10 07:29:24 root flanneld-start[2868]: runtime stack:
Jul 10 07:29:24 root flanneld-start[2868]: runtime.throw(0x1a7f7cf, 0x2a)
Jul 10 07:29:24 root flanneld-start[2868]:         /usr/local/go/src/runtime/panic.go:605 +0x95
Jul 10 07:29:24 root flanneld-start[2868]: runtime.sigpanic()
Jul 10 07:29:24 root flanneld-start[2868]:         /usr/local/go/src/runtime/signal_unix.go:351 +0x2b8
Jul 10 07:29:24 root flanneld-start[2868]: goroutine 55 [syscall, locked to thread]:
Jul 10 07:29:24 root flanneld-start[2868]: runtime.cgocall(0x15273b0, 0xc42002f5e8, 0x1a7d72e)
Jul 10 07:29:24 root flanneld-start[2868]:         /usr/local/go/src/runtime/cgocall.go:132 +0xe4 fp=0xc42002f5a8 sp=0xc42002f568 pc=0x402514
Jul 10 07:29:24 root flanneld-start[2868]: net._C2func_getaddrinfo(0x7fd8100008c0, 0x0, 0xc4203253e0, 0xc42010a150, 0x0, 0x0, 0x0)
Jul 10 07:29:24 root flanneld-start[2868]:         net/_obj/_cgo_gotypes.go:86 +0x5f fp=0xc42002f5e8 sp=0xc42002f5a8 pc=0x52081f
Jul 10 07:29:24 root flanneld-start[2868]: net.cgoLookupIPCNAME.func2(0x7fd8100008c0, 0x0, 0xc4203253e0, 0xc42010a150, 0xc420067a40, 0xc4205c27e0, 0x5)
Jul 10 07:29:24 root flanneld-start[2868]:         /usr/local/go/src/net/cgo_unix.go:151 +0x13f fp=0xc42002f640 sp=0xc42002f5e8 pc=0x527dbf
Jul 10 07:29:24 root flanneld-start[2868]: net.cgoLookupIPCNAME(0xc4205c27e0, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
Jul 10 07:29:24 root flanneld-start[2868]:         /usr/local/go/src/net/cgo_unix.go:151 +0x175 fp=0xc42002f738 sp=0xc42002f640 pc=0x522075
Jul 10 07:29:24 root flanneld-start[2868]: net.cgoIPLookup(0xc420067bc0, 0xc4205c27e0, 0x5)
Jul 10 07:29:24 root flanneld-start[2868]:         /usr/local/go/src/net/cgo_unix.go:203 +0x4d fp=0xc42002f7c8 sp=0xc42002f738 pc=0x5227bd
Jul 10 07:29:24 root flanneld-start[2868]: runtime.goexit()
Jul 10 07:29:24 root flanneld-start[2868]:         /usr/local/go/src/runtime/asm_amd64.s:2337 +0x1 fp=0xc42002f7d0 sp=0xc42002f7c8 pc=0x4598f1
Jul 10 07:29:24 root flanneld-start[2868]: created by net.cgoLookupIP
Jul 10 07:29:24 root flanneld-start[2868]:         /usr/local/go/src/net/cgo_unix.go:213 +0xaf
Jul 10 07:29:24 root flanneld-start[2868]: goroutine 1 [select]:
Jul 10 07:29:24 root flanneld-start[2868]: github.com/coreos/flannel/vendor/github.com/coreos/etcd/client.(*simpleHTTPClient).Do(0xc4205cd180, 0x7fd8302712b8, 0xc
Jul 10 07:29:24 root flanneld-start[2868]:         /go/src/github.com/coreos/flannel/vendor/github.com/coreos/etcd/client/client.go:531 +0x31d
Jul 10 07:29:24 root flanneld-start[2868]: github.com/coreos/flannel/vendor/github.com/coreos/etcd/client.(*redirectFollowingHTTPClient).Do(0xc42057d920, 0x7fd830
Jul 10 07:29:24 root flanneld-start[2868]:         /go/src/github.com/coreos/flannel/vendor/github.com/coreos/etcd/client/client.go:603 +0xb2
Jul 10 07:29:24 root flanneld-start[2868]: github.com/coreos/flannel/vendor/github.com/coreos/etcd/client.(*httpClusterClient).Do(0xc420067500, 0x7fd8302712b8, 0x
Jul 10 07:29:24 root flanneld-start[2868]:         /go/src/github.com/coreos/flannel/vendor/github.com/coreos/etcd/client/client.go:360 +0x36c
Jul 10 07:29:24 root flanneld-start[2868]: github.com/coreos/flannel/vendor/github.com/coreos/etcd/client.(*httpKeysAPI).Get(0xc42057d8c0, 0x7fd8302712b8, 0xc4205
Jul 10 07:29:24 root flanneld-start[2868]:         /go/src/github.com/coreos/flannel/vendor/github.com/coreos/etcd/client/keys.go:422 +0xe1
Jul 10 07:29:24 root flanneld-start[2868]: github.com/coreos/flannel/subnet/etcdv2.(*etcdSubnetRegistry).getNetworkConfig(0xc420324cc0, 0x7fd8302712b8, 0xc4205c96
Jul 10 07:29:24 root flanneld-start[2868]:         /go/src/github.com/coreos/flannel/subnet/etcdv2/registry.go:117 +0x125
Jul 10 07:29:24 root flanneld-start[2868]: github.com/coreos/flannel/subnet/etcdv2.(*LocalManager).GetNetworkConfig(0xc42057d8e0, 0x7fd8302712b8, 0xc4205c9600, 0x
Jul 10 07:29:24 root flanneld-start[2868]:         /go/src/github.com/coreos/flannel/subnet/etcdv2/local_manager.go:88 +0x4b
Jul 10 07:29:24 root flanneld-start[2868]: main.getConfig(0x7fd8302712b8, 0xc4205c9600, 0x284ffc0, 0xc42057d8e0, 0xc420067560, 0xc420231a00, 0xc4205c27d0)
Jul 10 07:29:24 root flanneld-start[2868]:         /go/src/github.com/coreos/flannel/main.go:347 +0xb2
Jul 10 07:29:24 root flanneld-start[2868]: main.main()
Jul 10 07:29:24 root flanneld-start[2868]:         /go/src/github.com/coreos/flannel/main.go:262 +0x595
Jul 10 07:29:24 root flanneld-start[2868]: goroutine 5 [syscall]:
Jul 10 07:29:24 root flanneld-start[2868]: os/signal.signal_recv(0x0)
Jul 10 07:29:24 root flanneld-start[2868]:         /usr/local/go/src/runtime/sigqueue.go:131 +0xa6
Jul 10 07:29:24 root flanneld-start[2868]: os/signal.loop()
Jul 10 07:29:24 root flanneld-start[2868]:         /usr/local/go/src/os/signal/signal_unix.go:22 +0x22
Jul 10 07:29:24 root flanneld-start[2868]: created by os/signal.init.0
Jul 10 07:29:24 root flanneld-start[2868]:         /usr/local/go/src/os/signal/signal_unix.go:28 +0x41
Jul 10 07:29:24 root flanneld-start[2868]: goroutine 6 [chan receive]:
Jul 10 07:29:24 root flanneld-start[2868]: github.com/coreos/flannel/vendor/github.com/golang/glog.(*loggingT).flushDaemon(0x28a94c0)
Jul 10 07:29:24 root flanneld-start[2868]:         /go/src/github.com/coreos/flannel/vendor/github.com/golang/glog/glog.go:879 +0x9f
Jul 10 07:29:24 root flanneld-start[2868]: created by github.com/coreos/flannel/vendor/github.com/golang/glog.init.0
Jul 10 07:29:24 root flanneld-start[2868]:         /go/src/github.com/coreos/flannel/vendor/github.com/golang/glog/glog.go:410 +0x203
Jul 10 07:29:24 root flanneld-start[2868]: goroutine 50 [select, locked to thread]:
Jul 10 07:29:24 root flanneld-start[2868]: runtime.gopark(0x1ad26a0, 0x0, 0x1a58035, 0x6, 0x18, 0x1)
Jul 10 07:29:24 root flanneld-start[2868]:         /usr/local/go/src/runtime/proc.go:287 +0x12c
Jul 10 07:29:24 root flanneld-start[2868]: runtime.selectgo(0xc420469f50, 0xc4200702a0)
Jul 10 07:29:24 root flanneld-start[2868]:         /usr/local/go/src/runtime/select.go:395 +0x1149
Jul 10 07:29:24 root flanneld-start[2868]: runtime.ensureSigM.func1()
Jul 10 07:29:24 root flanneld-start[2868]:         /usr/local/go/src/runtime/signal_unix.go:511 +0x220
Jul 10 07:29:24 root flanneld-start[2868]: runtime.goexit()
Jul 10 07:29:24 root flanneld-start[2868]:         /usr/local/go/src/runtime/asm_amd64.s:2337 +0x1
Jul 10 07:29:24 root flanneld-start[2868]: goroutine 51 [select]:
Jul 10 07:29:24 root flanneld-start[2868]: main.shutdownHandler(0x7fd8302712b8, 0xc4205c9600, 0xc420067560, 0xc420231a00)
Jul 10 07:29:24 root flanneld-start[2868]:         /go/src/github.com/coreos/flannel/main.go:331 +0xf2
Jul 10 07:29:24 root flanneld-start[2868]: main.main.func1(0x7fd8302712b8, 0xc4205c9600, 0xc420067560, 0xc420231a00, 0xc4205c27d0)
Jul 10 07:29:24 root flanneld-start[2868]:         /go/src/github.com/coreos/flannel/main.go:252 +0x49
Jul 10 07:29:24 root flanneld-start[2868]: created by main.main
Jul 10 07:29:24 root flanneld-start[2868]:         /go/src/github.com/coreos/flannel/main.go:251 +0x553
Jul 10 07:29:24 root flanneld-start[2868]: goroutine 52 [select]:
Jul 10 07:29:24 root flanneld-start[2868]: net/http.(*Transport).getConn(0xc42032c000, 0xc420324f30, 0x0, 0xc420070420, 0x4, 0xc4205c27e0, 0xa, 0x0, 0x0, 0x0)
Jul 10 07:29:24 root flanneld-start[2868]:         /usr/local/go/src/net/http/transport.go:948 +0x5bf
Jul 10 07:29:24 root flanneld-start[2868]: net/http.(*Transport).RoundTrip(0xc42032c000, 0xc42046e400, 0x0, 0x0, 0x0)
Jul 10 07:29:24 root flanneld-start[2868]:         /usr/local/go/src/net/http/transport.go:400 +0x6a6
Jul 10 07:29:24 root flanneld-start[2868]: github.com/coreos/flannel/vendor/github.com/coreos/etcd/client.(*simpleHTTPClient).Do.func1(0xc4205cd180, 0xc42046e400,
Jul 10 07:29:24 root flanneld-start[2868]:         /go/src/github.com/coreos/flannel/vendor/github.com/coreos/etcd/client/client.go:523 +0x41
Jul 10 07:29:24 root flanneld-start[2868]: created by github.com/coreos/flannel/vendor/github.com/coreos/etcd/client.(*simpleHTTPClient).Do
Jul 10 07:29:24 root flanneld-start[2868]:         /go/src/github.com/coreos/flannel/vendor/github.com/coreos/etcd/client/client.go:522 +0x200
Jul 10 07:29:24 root flanneld-start[2868]: goroutine 53 [select]:
Jul 10 07:29:24 root flanneld-start[2868]: net.(*Resolver).LookupIPAddr(0x28a7580, 0x284d920, 0xc420067a40, 0xc4205c27e0, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0)
Jul 10 07:29:24 root flanneld-start[2868]:         /usr/local/go/src/net/lookup.go:196 +0x52b
Jul 10 07:29:24 root flanneld-start[2868]: net.(*Resolver).internetAddrList(0x28a7580, 0x284d920, 0xc420067a40, 0x1a55550, 0x3, 0xc4205c27e0, 0xa, 0x0, 0x0, 0x0, 
Jul 10 07:29:24 root flanneld-start[2868]:         /usr/local/go/src/net/ipsock.go:293 +0x644
Jul 10 07:29:24 root flanneld-start[2868]: net.(*Resolver).resolveAddrList(0x28a7580, 0x284d920, 0xc420067a40, 0x1a55bae, 0x4, 0x1a55550, 0x3, 0xc4205c27e0, 0xa, 
Jul 10 07:29:24 root flanneld-start[2868]:         /usr/local/go/src/net/dial.go:193 +0x594
Jul 10 07:29:24 root flanneld-start[2868]: net.(*Dialer).DialContext(0xc420067440, 0x284d8e0, 0xc42001a040, 0x1a55550, 0x3, 0xc4205c27e0, 0xa, 0x0, 0x0, 0x0, ...)
Jul 10 07:29:24 root flanneld-start[2868]:         /usr/local/go/src/net/dial.go:375 +0x248
Jul 10 07:29:24 root flanneld-start[2868]: net.(*Dialer).Dial(0xc420067440, 0x1a55550, 0x3, 0xc4205c27e0, 0xa, 0x240020070720, 0x110, 0x110, 0xc42044c7e0)
Jul 10 07:29:24 root flanneld-start[2868]:         /usr/local/go/src/net/dial.go:320 +0x75
Jul 10 07:29:24 root flanneld-start[2868]: net.(*Dialer).Dial-fm(0x1a55550, 0x3, 0xc4205c27e0, 0xa, 0xc420231ac0, 0xc420045998, 0x404409, 0x60)
Jul 10 07:29:24 root flanneld-start[2868]:         /go/src/github.com/coreos/flannel/vendor/github.com/coreos/etcd/client/client.go:52 +0x52
Jul 10 07:29:24 root flanneld-start[2868]: net/http.(*Transport).dial(0xc42032c000, 0x284d8e0, 0xc42001a040, 0x1a55550, 0x3, 0xc4205c27e0, 0xa, 0x0, 0x0, 0x0, ...
Jul 10 07:29:24 root flanneld-start[2868]:         /usr/local/go/src/net/http/transport.go:887 +0x7b
Jul 10 07:29:24 root flanneld-start[2868]: net/http.(*Transport).dialConn(0xc42032c000, 0x284d8e0, 0xc42001a040, 0x0, 0xc420070420, 0x4, 0xc4205c27e0, 0xa, 0xc420
Jul 10 07:29:24 root flanneld-start[2868]:         /usr/local/go/src/net/http/transport.go:1060 +0x1d62
Jul 10 07:29:24 root flanneld-start[2868]: net/http.(*Transport).getConn.func4(0xc42032c000, 0x284d8e0, 0xc42001a040, 0xc420324f60, 0xc4200705a0)
Jul 10 07:29:24 root flanneld-start[2868]:         /usr/local/go/src/net/http/transport.go:943 +0x78
Jul 10 07:29:24 root flanneld-start[2868]: created by net/http.(*Transport).getConn
Jul 10 07:29:24 root flanneld-start[2868]:         /usr/local/go/src/net/http/transport.go:942 +0x393
Jul 10 07:29:24 root flanneld-start[2868]: goroutine 54 [select]:
Jul 10 07:29:24 root flanneld-start[2868]: net.cgoLookupIP(0x284d920, 0xc420067a40, 0xc4205c27e0, 0x5, 0xc420324f30, 0x0, 0xc420070420, 0x0, 0x0, 0x0)
Jul 10 07:29:24 root flanneld-start[2868]:         /usr/local/go/src/net/cgo_unix.go:214 +0x1b0
Jul 10 07:29:24 root flanneld-start[2868]: net.(*Resolver).lookupIP(0x28a7580, 0x284d920, 0xc420067a40, 0xc4205c27e0, 0x5, 0x0, 0x17ebf00, 0xc420324d20, 0x0, 0x0)
Jul 10 07:29:24 root flanneld-start[2868]:         /usr/local/go/src/net/lookup_unix.go:95 +0x12d
Jul 10 07:29:24 root flanneld-start[2868]: net.(*Resolver).(net.lookupIP)-fm(0x284d920, 0xc420067a40, 0xc4205c27e0, 0x5, 0x0, 0x0, 0x6a1d50, 0xc42032c000, 0x0)
Jul 10 07:29:24 root flanneld-start[2868]:         /usr/local/go/src/net/lookup.go:187 +0x56
Jul 10 07:29:24 root flanneld-start[2868]: net.glob..func10(0x284d920, 0xc420067a40, 0xc420231b00, 0xc4205c27e0, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0)
Jul 10 07:29:24 root flanneld-start[2868]:         /usr/local/go/src/net/hook.go:19 +0x52
Jul 10 07:29:24 root flanneld-start[2868]: net.(*Resolver).LookupIPAddr.func1(0xc42032c000, 0x284d8e0, 0xc42001a040, 0x0)
Jul 10 07:29:24 root flanneld-start[2868]:         /usr/local/go/src/net/lookup.go:193 +0x5c
Jul 10 07:29:24 root flanneld-start[2868]: internal/singleflight.(*Group).doCall(0x28a7570, 0xc4205cb130, 0xc4205c27e0, 0x5, 0xc420325080)
Jul 10 07:29:24 root flanneld-start[2868]:         /usr/local/go/src/internal/singleflight/singleflight.go:93 +0x2e
Jul 10 07:29:24 root flanneld-start[2868]: created by internal/singleflight.(*Group).DoChan
Jul 10 07:29:24 root flanneld-start[2868]:         /usr/local/go/src/internal/singleflight/singleflight.go:86 +0x31f
Jul 10 07:29:24 root systemd[1]: flanneld.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jul 10 07:29:24 root systemd[1]: flanneld.service: Failed with result 'exit-code'.
Jul 10 07:29:24 root systemd[1]: Failed to start Flanneld overlay address etcd agent.
```
I can start up at another node, the difference between these 2 nodes is the OS, the success one is ubuntu 16.04, the failed one is ubuntu 18.04

Your Environment
* Flannel version: v0.10.0
* Backend used (e.g. vxlan or udp): vxlan
* Etcd version: 3.3.9
* Operating System and version: Ubuntu 18.04.2 LTS

**Comment by gp0014** [comment]
I found the problem is I add etcd host ip to `/etcd/hosts`, and used this name in `-etcd-endpoints`. after I changed `-etcd-endpoints` to use etcd ip directly, it works.

**Comment by rajatchopra** [comment]
Closing this issue as per above comment. Probable action item to see why we crash instead of erroring nicely.
/cc @arasananbu
