### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference [signal 0xb code=0x1 addr=0x0]

### ISSUE THREAD

**Issue by sujitfulse** [coreos/flannel#348]
Hi, I have built etcd and flannel on my system. I have setup etcd cluster too ( two VMs ). When i am running running ./flanneld -iface=eth0 &, i am getting "panic: runtime error: invalid memory address or nil pointer dereference [signal 0xb code=0x1 addr=0x0]".  My OS is Ubuntu 15.10 .

etcd log on first node
```
root@ubuntu:/home/etcd# bin/etcd -name infra0 -initial-advertise-peer-urls http://192.168.122.36:2380   -listen-peer-urls http://192.168.122.36:2380   -listen-client-urls http://192.168.122.36:2379,http://127.0.0.1:2379   -advertise-client-urls http://192.168.122.36:2379   -initial-cluster-token etcd-cluster-1   -initial-cluster infra0=http://192.168.122.36:2380,infra2=http://192.168.122.193:2380 --election-timeout 1000 --heartbeat-interval 150  -initial-cluster-state new
2015/10/20 06:16:22 etcd: no data-dir provided, using default data-dir ./infra0.etcd
2015/10/20 06:16:22 etcd: listening for peers on http://192.168.122.36:2380
2015/10/20 06:16:22 etcd: listening for client requests on http://127.0.0.1:2379
2015/10/20 06:16:22 etcd: listening for client requests on http://192.168.122.36:2379
2015/10/20 06:16:22 etcdserver: datadir is valid for the 2.0.1 format
2015/10/20 06:16:22 etcdserver: name = infra0
2015/10/20 06:16:22 etcdserver: data dir = infra0.etcd
2015/10/20 06:16:22 etcdserver: member dir = infra0.etcd/member
2015/10/20 06:16:22 etcdserver: heartbeat = 150ms
2015/10/20 06:16:22 etcdserver: election = 900ms
2015/10/20 06:16:22 etcdserver: snapshot count = 10000
2015/10/20 06:16:22 etcdserver: advertise client URLs = http://192.168.122.36:2379
2015/10/20 06:16:22 etcdserver: initial advertise peer URLs = http://192.168.122.36:2380
2015/10/20 06:16:22 etcdserver: initial cluster = infra0=http://192.168.122.36:2380,infra2=http://192.168.122.193:2380
2015/10/20 06:16:22 etcdserver: start member 8d495f0a22da5e in cluster ecde20d529f1eba0
2015/10/20 06:16:22 raft: 8d495f0a22da5e became follower at term 0
2015/10/20 06:16:22 raft: newRaft 8d495f0a22da5e [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
2015/10/20 06:16:22 raft: 8d495f0a22da5e became follower at term 1
2015/10/20 06:16:22 etcdserver: added local member 8d495f0a22da5e [http://192.168.122.36:2380] to cluster ecde20d529f1eba0
2015/10/20 06:16:22 etcdserver: added member c61e2a519a899a7f [http://192.168.122.193:2380] to cluster ecde20d529f1eba0
2015/10/20 06:16:23 raft: 8d495f0a22da5e is starting a new election at term 1
2015/10/20 06:16:23 raft: 8d495f0a22da5e became candidate at term 2
2015/10/20 06:16:23 raft: 8d495f0a22da5e received vote from 8d495f0a22da5e at term 2
2015/10/20 06:16:23 raft: 8d495f0a22da5e [logterm: 1, index: 2] sent vote request to c61e2a519a899a7f at term 2
2015/10/20 06:16:23 raft: 8d495f0a22da5e received vote from c61e2a519a899a7f at term 2
2015/10/20 06:16:23 raft: 8d495f0a22da5e [q:2] has received 2 votes and 0 vote rejections
2015/10/20 06:16:23 raft: 8d495f0a22da5e became leader at term 2
2015/10/20 06:16:23 raft.node: 8d495f0a22da5e elected leader 8d495f0a22da5e at term 2
2015/10/20 06:16:24 etcdserver: published {Name:infra0 ClientURLs:[http://192.168.122.36:2379]} to cluster ecde20d529f1eba0
```
etcd log on second node
```
root@ubuntu:/home/etcd# bin/etcd -name infra2 -initial-advertise-peer-urls http://192.168.122.193:2380   -listen-peer-urls http://192.168.122.193:2380   -listen-client-urls http://192.168.122.193:2379,http://127.0.0.1:2379   -advertise-client-urls http://192.168.122.193:2379   -initial-cluster-token etcd-cluster-1   -initial-cluster infra0=http://192.168.122.36:2380,infra2=http://192.168.122.193:2380 --election-timeout 1000 --heartbeat-interval 150  -initial-cluster-state new
2015/10/20 06:16:23 etcd: no data-dir provided, using default data-dir ./infra2.etcd
2015/10/20 06:16:23 etcd: listening for peers on http://192.168.122.193:2380
2015/10/20 06:16:23 etcd: listening for client requests on http://127.0.0.1:2379
2015/10/20 06:16:23 etcd: listening for client requests on http://192.168.122.193:2379
2015/10/20 06:16:23 etcdserver: datadir is valid for the 2.0.1 format
2015/10/20 06:16:23 etcdserver: name = infra2
2015/10/20 06:16:23 etcdserver: data dir = infra2.etcd
2015/10/20 06:16:23 etcdserver: member dir = infra2.etcd/member
2015/10/20 06:16:23 etcdserver: heartbeat = 150ms
2015/10/20 06:16:23 etcdserver: election = 900ms
2015/10/20 06:16:23 etcdserver: snapshot count = 10000
2015/10/20 06:16:23 etcdserver: advertise client URLs = http://192.168.122.193:2379
2015/10/20 06:16:23 etcdserver: initial advertise peer URLs = http://192.168.122.193:2380
2015/10/20 06:16:23 etcdserver: initial cluster = infra0=http://192.168.122.36:2380,infra2=http://192.168.122.193:2380
2015/10/20 06:16:23 etcdserver: start member c61e2a519a899a7f in cluster ecde20d529f1eba0
2015/10/20 06:16:23 raft: c61e2a519a899a7f became follower at term 0
2015/10/20 06:16:23 raft: newRaft c61e2a519a899a7f [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
2015/10/20 06:16:23 raft: c61e2a519a899a7f became follower at term 1
2015/10/20 06:16:23 etcdserver: added member 8d495f0a22da5e [http://192.168.122.36:2380] to cluster ecde20d529f1eba0
2015/10/20 06:16:23 etcdserver: added local member c61e2a519a899a7f [http://192.168.122.193:2380] to cluster ecde20d529f1eba0
2015/10/20 06:16:23 raft: c61e2a519a899a7f [term: 1] received a MsgVote message with higher term from 8d495f0a22da5e [term: 2]
2015/10/20 06:16:23 raft: c61e2a519a899a7f became follower at term 2
2015/10/20 06:16:23 raft: c61e2a519a899a7f [logterm: 1, index: 2, vote: 0] voted for 8d495f0a22da5e [logterm: 1, index: 2] at term 2
2015/10/20 06:16:24 raft.node: c61e2a519a899a7f elected leader 8d495f0a22da5e at term 2
2015/10/20 06:16:24 rafthttp: starting client stream to 8d495f0a22da5e at term 2
2015/10/20 06:16:24 etcdserver: published {Name:infra2 ClientURLs:[http://192.168.122.193:2379]} to cluster ecde20d529f1eba0
```
Now i ran flanneld on my first node
```
root@ubuntu:/home/flannel/bin# ./flanneld -iface=eth0 &
[1] 4992
root@ubuntu:/home/flannel/bin# I1020 05:59:13.897450 04992 main.go:275] Installing signal handlers
I1020 05:59:13.899223 04992 main.go:189] Using 192.168.122.36 as external interface
go-etcd2015/10/20 05:59:13 DEBUG: get /coreos.com/network/config [http://127.0.0.1:2379]
go-etcd2015/10/20 05:59:13 DEBUG: Connecting to etcd: attempt 1 for keys/coreos.com/network/config?quorum=false&recursive=false&sorted=false
go-etcd2015/10/20 05:59:13 DEBUG: send.request.to http://127.0.0.1:2379/v2/keys/coreos.com/network/config?quorum=false&recursive=false&sorted=false | method GET
go-etcd2015/10/20 05:59:13 DEBUG: recv.response.from 
go-etcd2015/10/20 05:59:13 DEBUG: recv.success 
go-etcd2015/10/20 05:59:13 DEBUG: get /coreos.com/network/config [http://127.0.0.1:2379]
go-etcd2015/10/20 05:59:13 DEBUG: Connecting to etcd: attempt 1 for keys/coreos.com/network/config?quorum=false&recursive=false&sorted=false
go-etcd2015/10/20 05:59:13 DEBUG: send.request.to http://127.0.0.1:2379/v2/keys/coreos.com/network/config?quorum=false&recursive=false&sorted=false | method GET
go-etcd2015/10/20 05:59:13 DEBUG: recv.response.from 
go-etcd2015/10/20 05:59:13 DEBUG: recv.success 
go-etcd2015/10/20 05:59:13 DEBUG: get /coreos.com/network/subnets [http://127.0.0.1:2379]
go-etcd2015/10/20 05:59:13 DEBUG: Connecting to etcd: attempt 1 for keys/coreos.com/network/subnets?quorum=false&recursive=true&sorted=false
go-etcd2015/10/20 05:59:13 DEBUG: send.request.to http://127.0.0.1:2379/v2/keys/coreos.com/network/subnets?quorum=false&recursive=true&sorted=false | method GET
go-etcd2015/10/20 05:59:13 DEBUG: recv.response.from 
go-etcd2015/10/20 05:59:13 DEBUG: recv.success 
I1020 05:59:13.902897 04992 etcd.go:136] Found lease (11.0.63.0/24) for current IP (192.168.122.36), reusing
go-etcd2015/10/20 05:59:13 DEBUG: put /coreos.com/network/subnets/11.0.63.0-24, {"PublicIP":"192.168.122.36"}, ttl: 86400, [http://127.0.0.1:2379]
go-etcd2015/10/20 05:59:13 DEBUG: Connecting to etcd: attempt 1 for keys/coreos.com/network/subnets/11.0.63.0-24
go-etcd2015/10/20 05:59:13 DEBUG: send.request.to http://127.0.0.1:2379/v2/keys/coreos.com/network/subnets/11.0.63.0-24 | method PUT
go-etcd2015/10/20 05:59:14 DEBUG: recv.response.from 
go-etcd2015/10/20 05:59:14 DEBUG: recv.success 
I1020 05:59:14.016817 04992 etcd.go:91] Subnet lease acquired: 11.0.63.0/24
I1020 05:59:14.018867 04992 udp.go:222] Watching for new subnet leases
go-etcd2015/10/20 05:59:14 DEBUG: get /coreos.com/network/subnets [http://127.0.0.1:2379]
go-etcd2015/10/20 05:59:14 DEBUG: Connecting to etcd: attempt 1 for keys/coreos.com/network/subnets?quorum=false&recursive=true&sorted=false
go-etcd2015/10/20 05:59:14 DEBUG: send.request.to http://127.0.0.1:2379/v2/keys/coreos.com/network/subnets?quorum=false&recursive=true&sorted=false | method GET
go-etcd2015/10/20 05:59:14 DEBUG: recv.response.from 
go-etcd2015/10/20 05:59:14 DEBUG: recv.success 
I1020 05:59:14.020343 04992 udp.go:247] Subnet added: 11.0.63.0/24
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0]

goroutine 28 [running]:
udp.setRoute
	/home/flannel/gopath/src/github.com/coreos/flannel/backend/udp/cproxy.go:66
github_com_coreos_flannel_backend_udp.processSubnetEvents.pN48_github_com_coreos_flannel_backend_udp.UdpBackend
	/home/flannel/gopath/src/github.com/coreos/flannel/backend/udp/udp.go:249
github_com_coreos_flannel_backend_udp.monitorEvents.pN48_github_com_coreos_flannel_backend_udp.UdpBackend
	/home/flannel/gopath/src/github.com/coreos/flannel/backend/udp/udp.go:235
github_com_coreos_flannel_backend_udp.Run.pN48_github_com_coreos_flannel_backend_udp.UdpBackend
	/home/flannel/gopath/src/github.com/coreos/flannel/backend/udp/udp.go:141
network.$nested4
	/home/flannel/gopath/src/github.com/coreos/flannel/network/network.go:109
created by github_com_coreos_flannel_network.Run.pN41_github_com_coreos_flannel_network.Network
	/home/flannel/gopath/src/github.com/coreos/flannel/network/network.go:108

goroutine 16 [chan receive]:
main.main
	/home/flannel/gopath/src/github.com/coreos/flannel/main.go:288

goroutine 18 [finalizer wait]:
created by runtime_createfing
	../../../src/libgo/runtime/mgc0.c:2572

goroutine 19 [syscall]:
	goroutine in C code; stack unavailable
created by os_signal..import
	../../../src/libgo/go/os/signal/signal_unix.go:25

goroutine 20 [chan receive]:
github_com_coreos_flannel_Godeps__workspace_src_github_com_golang_glog.flushDaemon.pN79_github_com_coreos_flannel_Godeps__workspace_src_github_com_golang_glog.loggingT
	/home/flannel/gopath/src/github.com/coreos/flannel/Godeps/_workspace/src/github.com/golang/glog/glog.go:839
created by glog.$init0
	/home/flannel/gopath/src/github.com/coreos/flannel/Godeps/_workspace/src/github.com/golang/glog/glog.go:406

goroutine 24 [chan receive]:
github_com_coreos_flannel_network.Run.pN41_github_com_coreos_flannel_network.Network
	/home/flannel/gopath/src/github.com/coreos/flannel/network/network.go:113
main.$nested2
	/home/flannel/gopath/src/github.com/coreos/flannel/main.go:217
created by main.initAndRun
	/home/flannel/gopath/src/github.com/coreos/flannel/main.go:199

goroutine 26 [IO wait]:
net.runtime_pollWait
	../../../src/libgo/runtime/netpoll.goc:151
net.Wait.pN12_net.pollDesc
	../../../src/libgo/go/net/fd_poll_runtime.go:84
net.WaitRead.pN12_net.pollDesc
	../../../src/libgo/go/net/fd_poll_runtime.go:89
net.Read.pN9_net.netFD
	../../../src/libgo/go/net/fd_unix.go:242
net.Read.pN8_net.conn
	../../../src/libgo/go/net/net.go:121
net.Read.pN11_net.TCPConn
	../../../src/libgo/go/net/tcpsock_posix.go:57
net_http.Read.N22_net_http.noteEOFReader
	../../../src/libgo/go/net/http/transport.go:1270
bufio.fill.pN12_bufio.Reader
	../../../src/libgo/go/bufio/bufio.go:97
bufio.Peek.pN12_bufio.Reader
	../../../src/libgo/go/bufio/bufio.go:132
net_http.readLoop.pN20_net_http.persistConn
	../../../src/libgo/go/net/http/transport.go:842
created by net_http.dialConn.pN18_net_http.Transport
	../../../src/libgo/go/net/http/transport.go:660

goroutine 27 [select]:
net_http.writeLoop.pN20_net_http.persistConn
	../../../src/libgo/go/net/http/transport.go:945
created by net_http.dialConn.pN18_net_http.Transport
	../../../src/libgo/go/net/http/transport.go:661

goroutine 29 [syscall]:
	goroutine in C code; stack unavailable
created by github_com_coreos_flannel_backend_udp.Run.pN48_github_com_coreos_flannel_backend_udp.UdpBackend
	/home/flannel/gopath/src/github.com/coreos/flannel/backend/udp/udp.go:131

goroutine 30 [select]:
github_com_coreos_flannel_subnet.LeaseRenewer
	/home/flannel/gopath/src/github.com/coreos/flannel/subnet/renew.go:32
udp.$nested1
	/home/flannel/gopath/src/github.com/coreos/flannel/backend/udp/udp.go:137
created by github_com_coreos_flannel_backend_udp.Run.pN48_github_com_coreos_flannel_backend_udp.UdpBackend
	/home/flannel/gopath/src/github.com/coreos/flannel/backend/udp/udp.go:136

goroutine 31 [select]:
github_com_coreos_flannel_subnet.watchSubnets.pN51_github_com_coreos_flannel_subnet.etcdSubnetRegistry
	/home/flannel/gopath/src/github.com/coreos/flannel/subnet/registry.go:151
github_com_coreos_flannel_subnet.WatchLeases.pN44_github_com_coreos_flannel_subnet.EtcdManager
	/home/flannel/gopath/src/github.com/coreos/flannel/subnet/etcd.go:313
github_com_coreos_flannel_subnet.WatchLeases
	/home/flannel/gopath/src/github.com/coreos/flannel/subnet/watch.go:33
udp.$nested2
	/home/flannel/gopath/src/github.com/coreos/flannel/backend/udp/udp.go:228
created by github_com_coreos_flannel_backend_udp.monitorEvents.pN48_github_com_coreos_flannel_backend_udp.UdpBackend
	/home/flannel/gopath/src/github.com/coreos/flannel/backend/udp/udp.go:227

goroutine 33 [runnable]:
created by github_com_coreos_flannel_subnet.watchSubnets.pN51_github_com_coreos_flannel_subnet.etcdSubnetRegistry
	/home/flannel/gopath/src/github.com/coreos/flannel/subnet/registry.go:129
```
can i know, what is going wrong..

My network config file is 

```
etcdctl mk /coreos.com/network/config '{"Network":"11.0.0.0/16"}' 
```

**Comment by jonboulle** [comment]
@sujitfulse what commit did you build flannel from?

**Comment by sujitfulse** [comment]
i was building with old commit. just now i cloned it with latest commit and it solved this problem. apologies .
```
root@ubuntu:/home/temp/flannel# git log -n2
commit 86ec8945474a159f20dbc6128f53b19471129aa3
Merge: 9889a4d 878c525
Author: Eugene Yakubovich <eyakubovich@gmail.com>
Date:   Sun Oct 18 15:06:37 2015 -0700
```
