### ISSUE TITLE
panic: ./flanneld flag redefined: log_dir

### ISSUE THREAD

**Issue by zhangyongsu** [coreos/flannel#497]
#./flanneld
    ./flanneld flag redefined: log_dir
    panic: ./flanneld flag redefined: log_dir

    goroutine 1 [running]:
    panic(0x76e0c0, 0xc42000c800)
	/root/golang/go/src/runtime/panic.go:500 +0x1a1
    flag.(*FlagSet).Var(0xc42009e060, 0xbac9e0, 0xc42000c7a0, 0x80276f, 0x7, 0x81294b, 0x2f)
	/root/golang/go/src/flag/flag.go:791 +0x43e
    flag.(*FlagSet).StringVar(0xc42009e060, 0xc42000c7a0, 0x80276f, 0x7, 0x0, 0x0, 0x81294b, 0x2f)
	/root/golang/go/src/flag/flag.go:694 +0x8b
    flag.(*FlagSet).String(0xc42009e060, 0x80276f, 0x7, 0x0, 0x0, 0x81294b, 0x2f, 0xc42000c790)
	/root/golang/go/src/flag/flag.go:707 +0x90
    flag.String(0x80276f, 0x7, 0x0, 0x0, 0x81294b, 0x2f, 0xc420079f30)
	/root/golang/go/src/flag/flag.go:714 +0x69
    github.com/coreos/flannel/vendor/github.com/golang/glog.init()
	/root/golang/src/github.com/coreos/flannel/vendor/github.com/golang/glog/glog_file.go:41 +0x143
    github.com/coreos/flannel/network.init()
	/root/golang/src/github.com/coreos/flannel/network/network.go:199 +0x58
    main.init()
	/root/flannel/main.go:171 +0x64`

go version
go version go1.7 linux/amd64

gcc version
gcc (Debian 4.9.2-10) 4.9.2
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by zhangyongsu** [comment]
I think it is for lost build file in 6.x version . I add it and ok now .
