### ISSUE TITLE
aws-vpc - Flannel doesn't start if the route is a black hole

### ISSUE THREAD

**Issue by arthur-c** [coreos/flannel#525]
Hi,

I used flannel over aws for more than a year and I just discoverd that I can't start flannel anymore if the route is in black hole state. It is easy to have a black hole route when you terminate and recreate an instance.

I am using CoreOS stable 1122.2.0, I had the error with flannel  0.5.5, I upgraded to v0.6.2 and I still got the problem.

The problem is solved when I delete the black hole route.

```
Oct 03 12:38:52 coreos-worker-21 systemd[1]: Starting Setup flannel network...
Oct 03 12:38:52 coreos-worker-21 etcdctl[2669]: { "Network": "172.37.0.0/29", "Backend": {"Type": "aws-vpc"} }
Oct 03 12:38:52 coreos-worker-21 systemd[1]: Started docker container 1de46bbb7560807d8978d09e6fa22b129946a1b4b6003d349b96819aa03bd95e.
Oct 03 12:38:52 coreos-worker-21 sdnotify-proxy[2679]: I1003 12:38:52.264120 00001 main.go:126] Installing signal handlers
Oct 03 12:38:52 coreos-worker-21 sdnotify-proxy[2679]: I1003 12:38:52.264303 00001 manager.go:133] Determining IP address of default interface
Oct 03 12:38:52 coreos-worker-21 sdnotify-proxy[2679]: I1003 12:38:52.264982 00001 manager.go:163] Using 172.31.35.70 as external interface
Oct 03 12:38:52 coreos-worker-21 sdnotify-proxy[2679]: I1003 12:38:52.265014 00001 manager.go:164] Using 172.31.35.70 as external endpoint
Oct 03 12:38:52 coreos-worker-21 sdnotify-proxy[2679]: I1003 12:38:52.280051 00001 local_manager.go:134] Found lease (172.37.0.4/30) for current IP (172.31.35.70), reusing
Oct 03 12:38:52 coreos-worker-21 sdnotify-proxy[2679]: I1003 12:38:52.492398 00001 awsvpc.go:100] RouteTableID not passed as config parameter, detecting ...
Oct 03 12:38:52 coreos-worker-21 sdnotify-proxy[2679]: I1003 12:38:52.604594 00001 awsvpc.go:212] Subnet-ID: subnet-b9bc3dc2
Oct 03 12:38:52 coreos-worker-21 sdnotify-proxy[2679]: I1003 12:38:52.604611 00001 awsvpc.go:213] VPC-ID: vpc-9a7d9af3
Oct 03 12:38:52 coreos-worker-21 sdnotify-proxy[2679]: I1003 12:38:52.741854 00001 awsvpc.go:106] RouteRouteTableID: rtb-4b628522
Oct 03 12:38:52 coreos-worker-21 systemd[1]: Started OpenSSH per-connection server daemon (172.31.30.20:43940).
Oct 03 12:38:52 coreos-worker-21 sshd[2733]: Did not receive identification string from 172.31.30.20
Oct 03 12:38:52 coreos-worker-21 sdnotify-proxy[2679]: panic: runtime error: invalid memory address or nil pointer dereference
Oct 03 12:38:52 coreos-worker-21 sdnotify-proxy[2679]: [signal 0xb code=0x1 addr=0x0 pc=0x4d15e0]
Oct 03 12:38:52 coreos-worker-21 sdnotify-proxy[2679]: goroutine 9 [running]:
Oct 03 12:38:52 coreos-worker-21 sdnotify-proxy[2679]: panic(0xb65400, 0xc820012070)
Oct 03 12:38:52 coreos-worker-21 sdnotify-proxy[2679]:         /usr/local/go/src/runtime/panic.go:481 +0x3e6
Oct 03 12:38:52 coreos-worker-21 sdnotify-proxy[2679]: github.com/coreos/flannel/backend/awsvpc.(*AwsVpcBackend).checkMatchingRoutes(0xc820108220, 0xc820462af0, 0xc, 0xc820108a80, 0x13, 0xc8204584b0, 0xd, 0xc82010c050, 0x0, 0x0, ...)
Oct 03 12:38:52 coreos-worker-21 sdnotify-proxy[2679]:         /go/src/github.com/coreos/flannel/backend/awsvpc/awsvpc.go:157 +0x740
Oct 03 12:38:52 coreos-worker-21 sdnotify-proxy[2679]: github.com/coreos/flannel/backend/awsvpc.(*AwsVpcBackend).RegisterNetwork(0xc820108220, 0x7f7ee9317088, 0xc82004d4c0, 0x0, 0x0, 0xc82014e050, 0x0, 0x0, 0x0, 0x0)
Oct 03 12:38:52 coreos-worker-21 sdnotify-proxy[2679]:         /go/src/github.com/coreos/flannel/backend/awsvpc/awsvpc.go:108 +0xb0e
Oct 03 12:38:52 coreos-worker-21 sdnotify-proxy[2679]: github.com/coreos/flannel/network.(*Network).init(0xc8200eae00, 0x0, 0x0)
Oct 03 12:38:52 coreos-worker-21 sdnotify-proxy[2679]:         /go/src/github.com/coreos/flannel/network/network.go:84 +0x235
Oct 03 12:38:52 coreos-worker-21 sdnotify-proxy[2679]: github.com/coreos/flannel/network.(*Network).retryInit(0xc8200eae00, 0x0, 0x0)
Oct 03 12:38:52 coreos-worker-21 sdnotify-proxy[2679]:         /go/src/github.com/coreos/flannel/network/network.go:101 +0x4d
Oct 03 12:38:52 coreos-worker-21 sdnotify-proxy[2679]: github.com/coreos/flannel/network.(*Network).runOnce(0xc8200eae00, 0xc82004d480, 0xc8204c5f30, 0x0, 0x0)
Oct 03 12:38:52 coreos-worker-21 sdnotify-proxy[2679]:         /go/src/github.com/coreos/flannel/network/network.go:117 +0x68
Oct 03 12:38:52 coreos-worker-21 sdnotify-proxy[2679]: github.com/coreos/flannel/network.(*Network).Run(0xc8200eae00, 0xc82004d480, 0xc8204c5f30)
Oct 03 12:38:52 coreos-worker-21 sdnotify-proxy[2679]:         /go/src/github.com/coreos/flannel/network/network.go:185 +0x39
Oct 03 12:38:52 coreos-worker-21 sdnotify-proxy[2679]: github.com/coreos/flannel/network.(*Manager).runNetwork(0xc820010900, 0xc8200eae00)
Oct 03 12:38:52 coreos-worker-21 sdnotify-proxy[2679]:         /go/src/github.com/coreos/flannel/network/manager.go:254 +0x4b
Oct 03 12:38:52 coreos-worker-21 sdnotify-proxy[2679]: github.com/coreos/flannel/network.(*Manager).Run.func1.1(0xc820010900, 0xc820013f80, 0xc8200eae00)
Oct 03 12:38:52 coreos-worker-21 sdnotify-proxy[2679]:         /go/src/github.com/coreos/flannel/network/manager.go:348 +0x2b
Oct 03 12:38:52 coreos-worker-21 sdnotify-proxy[2679]: created by github.com/coreos/flannel/network.(*Manager).Run.func1
Oct 03 12:38:52 coreos-worker-21 sdnotify-proxy[2679]:         /go/src/github.com/coreos/flannel/network/manager.go:350 +0x6d
Oct 03 12:38:52 coreos-worker-21 systemd[1]: Stopped docker container 1de46bbb7560807d8978d09e6fa22b129946a1b4b6003d349b96819aa03bd95e.
Oct 03 12:38:52 coreos-worker-21 systemd[1]: flanneld.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Oct 03 12:38:52 coreos-worker-21 systemd[1]: Failed to start Setup flannel network.
Oct 03 12:38:52 coreos-worker-21 systemd[1]: flanneld.service: Unit entered failed state.
Oct 03 12:38:52 coreos-worker-21 systemd[1]: flanneld.service: Failed with result 'exit-code'.
Oct 03 12:38:58 coreos-worker-21 systemd[1]: flanneld.service: Service hold-off time over, scheduling restart.
Oct 03 12:38:58 coreos-worker-21 systemd[1]: Stopped Setup flannel network.
```

I removed the black hole route and it's now fine:

```
Oct 03 12:38:58 coreos-worker-21 systemd[1]: Starting Setup flannel network...
Oct 03 12:38:58 coreos-worker-21 etcdctl[2756]: { "Network": "172.37.0.0/29", "Backend": {"Type": "aws-vpc"} }
Oct 03 12:38:58 coreos-worker-21 systemd[1]: Started docker container 9176363c5237436a9076cff87246322d63932ff1f043c372e0a862200a73377d.
Oct 03 12:38:58 coreos-worker-21 sdnotify-proxy[2766]: I1003 12:38:58.251372 00001 main.go:126] Installing signal handlers
Oct 03 12:38:58 coreos-worker-21 sdnotify-proxy[2766]: I1003 12:38:58.251454 00001 manager.go:133] Determining IP address of default interface
Oct 03 12:38:58 coreos-worker-21 sdnotify-proxy[2766]: I1003 12:38:58.251621 00001 manager.go:163] Using 172.31.35.70 as external interface
Oct 03 12:38:58 coreos-worker-21 sdnotify-proxy[2766]: I1003 12:38:58.251639 00001 manager.go:164] Using 172.31.35.70 as external endpoint
Oct 03 12:38:58 coreos-worker-21 sdnotify-proxy[2766]: I1003 12:38:58.271151 00001 local_manager.go:134] Found lease (172.37.0.4/30) for current IP (172.31.35.70), reusing
Oct 03 12:38:58 coreos-worker-21 sdnotify-proxy[2766]: I1003 12:38:58.458263 00001 awsvpc.go:100] RouteTableID not passed as config parameter, detecting ...
Oct 03 12:38:58 coreos-worker-21 sdnotify-proxy[2766]: I1003 12:38:58.582958 00001 awsvpc.go:212] Subnet-ID: subnet-b9bc3dc2
Oct 03 12:38:58 coreos-worker-21 sdnotify-proxy[2766]: I1003 12:38:58.582975 00001 awsvpc.go:213] VPC-ID: vpc-9a7d9af3
Oct 03 12:38:58 coreos-worker-21 sdnotify-proxy[2766]: I1003 12:38:58.714034 00001 awsvpc.go:106] RouteRouteTableID: rtb-4b628522
Oct 03 12:38:58 coreos-worker-21 sdnotify-proxy[2766]: I1003 12:38:58.967630 00001 ipmasq.go:47] Adding iptables rule: -s 172.37.0.0/29 -d 172.37.0.0/29 -j RETURN
Oct 03 12:38:58 coreos-worker-21 sdnotify-proxy[2766]: I1003 12:38:58.969611 00001 ipmasq.go:47] Adding iptables rule: -s 172.37.0.0/29 ! -d 224.0.0.0/4 -j MASQUERADE
Oct 03 12:38:58 coreos-worker-21 sdnotify-proxy[2766]: I1003 12:38:58.971285 00001 ipmasq.go:47] Adding iptables rule: ! -s 172.37.0.0/29 -d 172.37.0.0/29 -j MASQUERADE
Oct 03 12:38:58 coreos-worker-21 sdnotify-proxy[2766]: I1003 12:38:58.973190 00001 manager.go:246] Lease acquired: 172.37.0.4/30
Oct 03 12:38:59 coreos-worker-21 systemd[1]: Started docker container 14e53475ba055e02703d0b9adfaa89569cc522863c22377478e367ce6336f466.
Oct 03 12:38:59 coreos-worker-21 kernel: SELinux: mount invalid.  Same superblock, different security settings for (dev mqueue, type mqueue)
Oct 03 12:38:59 coreos-worker-21 systemd[1]: Stopped docker container 14e53475ba055e02703d0b9adfaa89569cc522863c22377478e367ce6336f466.
Oct 03 12:38:59 coreos-worker-21 systemd[1]: Started Setup flannel network.
```

My cloud-config:

```   
 - name: flanneld.service
      drop-ins:
        - name: 50-network-config.conf
          content: |
            [Unit]
            Description=Setup flannel network
            Wants=setup-etcdctl-env.service
            After=setup-etcdctl-env.service

            [Service]
            EnvironmentFile=/etc/environment
            ExecStartPre=/usr/bin/etcdctl set /coreos.com/network/hazelcast_1/config '{ "Network": "{{ flannel_networks.hazelcast_1.subnet }}", "Backend": {"Type": "aws-vpc"} }'
      command: start

    - name: flanneld.service
      command: start
      content: |
          [Unit]
          Description=Network fabric for containers
          Documentation=https://github.com/coreos/flannel
          Requires=early-docker.service
          After=etcd2.service early-docker.service
          Before=early-docker.target

          [Service]
          Type=notify
          Restart=always
          RestartSec=5
          Environment="TMPDIR=/var/tmp/"
          Environment="DOCKER_HOST=unix:///var/run/early-docker.sock"
          Environment="FLANNEL_VER={{ flannel_networks.hazelcast_1.flannel_version }}"
          Environment="ETCD_SSL_DIR=/etc/ssl/etcd"
          LimitNOFILE=40000
          LimitNPROC=1048576
          ExecStartPre=/sbin/modprobe ip_tables
          ExecStartPre=/usr/bin/mkdir -p /run/flannel
          ExecStartPre=/usr/bin/mkdir -p ${ETCD_SSL_DIR}
          ExecStartPre=/usr/bin/touch /run/flannel/options.env

          ExecStart=/usr/libexec/sdnotify-proxy /run/flannel/sd.sock \
            /usr/bin/docker run --net=host --privileged=true --rm \
            --volume=/run/flannel:/run/flannel \
            --env=NOTIFY_SOCKET=/run/flannel/sd.sock \
            --env-file=/run/flannel/options.env \
            --volume=/usr/share/ca-certificates:/etc/ssl/certs:ro \
            --volume=${ETCD_SSL_DIR}:/etc/ssl/etcd:ro \
            quay.io/coreos/flannel:${FLANNEL_VER} /opt/bin/flanneld --ip-masq=true --etcd-prefix=/coreos.com/network/hazelcast_1/

          # Update docker options
          ExecStartPost=/usr/bin/docker run --net=host --rm -v /run:/run \
            quay.io/coreos/flannel:${FLANNEL_VER} \
            /opt/bin/mk-docker-opts.sh -d /run/flannel_docker_opts.env -i
```

**Comment by monder** [comment]
It seems it's not due to the blackhole. Could you please check if your route has any vpc-endpoints and PR (#523)
It is kinda a rare case since `vpc-endpoints` are usually at the end of the array, and the function returns before them, but sometimes when you launch/terminate machines frequently you may end up with situation where the new lease you got (172.37.0.4) is actually a blackhole from the instance long time ago.

**Comment by arthur-c** [comment]
That's exactly my case:

the last entry in my table:

```
               {
                    "GatewayId": "vpce-xx", 
                    "Origin": "CreateRoute", 
                    "State": "active", 
                    "DestinationPrefixListId": "pl-xxx"
                }
```

I'll wait for the patch release, thanks.
