### ISSUE TITLE
Flannel (with the kube-subnet-mgr) produces an error on shutdown

### ISSUE THREAD

**Issue by tomdee** [coreos/flannel#668]
Seen on current master but I think this is in 0.7.0 too
```
I0411 22:42:03.654633       1 kube.go:108] Waiting 10m0s for node controller to sync
I0411 22:42:03.654698       1 kube.go:288] starting kube subnet manager
I0411 22:42:04.655271       1 kube.go:115] Node controller sync successful
I0411 22:42:04.655311       1 main.go:120] Installing signal handlers
I0411 22:42:04.655764       1 manager.go:136] Determining IP address of default interface
I0411 22:42:04.656484       1 manager.go:149] Using interface with name eth0 and address 10.0.2.15
I0411 22:42:04.656512       1 manager.go:166] Defaulting external address to interface address (10.0.2.15)
I0411 22:42:04.659646       1 ipmasq.go:47] Adding iptables rule: -s 10.33.0.0/16 -d 10.33.0.0/16 -j RETURN
I0411 22:42:04.663399       1 ipmasq.go:47] Adding iptables rule: -s 10.33.0.0/16 ! -d 224.0.0.0/4 -j MASQUERADE
I0411 22:42:04.667921       1 ipmasq.go:47] Adding iptables rule: ! -s 10.33.0.0/16 -d 10.33.0.0/16 -j MASQUERADE
I0411 22:42:04.673330       1 manager.go:250] Lease acquired: 10.33.12.0/24
I0411 22:42:04.674037       1 network.go:51] Watching for new subnet leases
I0411 22:42:21.533761       1 main.go:149] Exiting...
panic: runtime error: index out of range

goroutine 38 [running]:
github.com/coreos/flannel/subnet.WatchLease(0x7f4ff0648238, 0xc4201826c0, 0x252e6e0, 0xc420222460, 0x0, 0x0, 0xa210c00, 0x18, 0xc42022d680)
        /home/tom/go/src/github.com/coreos/flannel/subnet/watch.go:283 +0x365
github.com/coreos/flannel/network.(*Network).runOnce.func2(0x7f4ff0648238, 0xc4201826c0, 0xc420126070, 0xc42022d680, 0xc42018c5f0)
        /home/tom/go/src/github.com/coreos/flannel/network/network.go:133 +0x96
created by github.com/coreos/flannel/network.(*Network).runOnce
        /home/tom/go/src/github.com/coreos/flannel/network/network.go:135 +0x1cd
```

**Comment by tomdee** [comment]
This is now fixed
