### ISSUE TITLE
cannot start flannel v0.10.0

### ISSUE THREAD

**Issue by shsjshentao** [coreos/flannel#977]
flannel v0.10.0 cannot start in some VMs. And v0.9.1 is ok in these VMs
backend is etcd v3.2.17
Configure etcd endpoint by IP is ok. By hostname will cause this problem.

The error log:
I0409 07:46:12.325829       1 main.go:475] Determining IP address of default interface
I0409 07:46:12.326898       1 main.go:488] Using interface with name ens32 and address 10.2.18.209
I0409 07:46:12.326940       1 main.go:505] Defaulting external address to interface address (10.2.18.209)
2018-04-09 07:46:12.329345 I | warning: ignoring ServerName for user-provided CA for backwards compatibility is deprecated
I0409 07:46:12.329487       1 main.go:235] Created subnet manager: Etcd Local Manager with Previous Subnet: None
I0409 07:46:12.329509       1 main.go:238] Installing signal handlers
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x63 pc=0x7f51049d460b]

runtime stack:
runtime.throw(0x1a7f7cf, 0x2a)
        /usr/local/go/src/runtime/panic.go:605 +0x95
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:351 +0x2b8

goroutine 54 [syscall, locked to thread]:
runtime.cgocall(0x15273b0, 0xc420463de8, 0x1a7d72e)
        /usr/local/go/src/runtime/cgocall.go:132 +0xe4 fp=0xc420463da8 sp=0xc420463d68 pc=0x402514
net._C2func_getaddrinfo(0x7f50f80008c0, 0x0, 0xc42029c690, 0xc420148040, 0x0, 0x0, 0x0)
        net/_obj/_cgo_gotypes.go:86 +0x5f fp=0xc420463de8 sp=0xc420463da8 pc=0x52081f
net.cgoLookupIPCNAME.func2(0x7f50f80008c0, 0x0, 0xc42029c690, 0xc420148040, 0xc4203ae4e0, 0xc420162140, 0x16)
        /usr/local/go/src/net/cgo_unix.go:151 +0x13f fp=0xc420463e40 sp=0xc420463de8 pc=0x527dbf
net.cgoLookupIPCNAME(0xc420162140, 0x16, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/cgo_unix.go:151 +0x175 fp=0xc420463f38 sp=0xc420463e40 pc=0x522075
net.cgoIPLookup(0xc4203ae660, 0xc420162140, 0x16)
        /usr/local/go/src/net/cgo_unix.go:203 +0x4d fp=0xc420463fc8 sp=0xc420463f38 pc=0x5227bd
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2337 +0x1 fp=0xc420463fd0 sp=0xc420463fc8 pc=0x4598f1
created by net.cgoLookupIP
        /usr/local/go/src/net/cgo_unix.go:213 +0xaf

goroutine 1 [select]:
github.com/coreos/flannel/vendor/github.com/coreos/etcd/client.(*simpleHTTPClient).Do(0xc42008f0e0, 0x7f50fe7bd1b0, 0xc4202e0280, 0x2838420, 0xc42029c000, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/coreos/flannel/vendor/github.com/coreos/etcd/client/client.go:531 +0x31d
github.com/coreos/flannel/vendor/github.com/coreos/etcd/client.(*redirectFollowingHTTPClient).Do(0xc42031c020, 0x7f50fe7bd1b0, 0xc4202e0280, 0x2838420, 0xc42029c000, 0x7fff352a2ebe, 0x1b, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/coreos/flannel/vendor/github.com/coreos/etcd/client/client.go:603 +0xb2
github.com/coreos/flannel/vendor/github.com/coreos/etcd/client.(*httpClusterClient).Do(0xc4200ff5c0, 0x7f50fe7bd1b0, 0xc4202e0280, 0x2838420, 0xc42029c000, 0xc42061fa88, 0xc42061faa8, 0x4119c8, 0x10, 0x18b1f20, ...)
        /go/src/github.com/coreos/flannel/vendor/github.com/coreos/etcd/client/client.go:360 +0x36c
github.com/coreos/flannel/vendor/github.com/coreos/etcd/client.(*httpKeysAPI).Get(0xc4202d8840, 0x7f50fe7bd1b0, 0xc4202e0280, 0xc420162120, 0x1a, 0xc420018080, 0xc420294001, 0x3, 0x4)
        /go/src/github.com/coreos/flannel/vendor/github.com/coreos/etcd/client/keys.go:422 +0xe1
github.com/coreos/flannel/subnet/etcdv2.(*etcdSubnetRegistry).getNetworkConfig(0xc4202d35c0, 0x7f50fe7bd1b0, 0xc4202e0280, 0x7f50fe7bd1b0, 0xc42061fbc8, 0x410dd6, 0x7f510793e558)
        /go/src/github.com/coreos/flannel/subnet/etcdv2/registry.go:117 +0x125
github.com/coreos/flannel/subnet/etcdv2.(*LocalManager).GetNetworkConfig(0xc4202d8860, 0x7f50fe7bd1b0, 0xc4202e0280, 0x453c10, 0x7f510793a6c8, 0x7f50fe7bd105)
        /go/src/github.com/coreos/flannel/subnet/etcdv2/local_manager.go:88 +0x4b
main.getConfig(0x7f50fe7bd1b0, 0xc4202e0280, 0x284ffc0, 0xc4202d8860, 0xc4200ff620, 0xc420294010, 0xc420018050)
        /go/src/github.com/coreos/flannel/main.go:347 +0xb2
main.main()
        /go/src/github.com/coreos/flannel/main.go:262 +0x595

goroutine 5 [syscall]:
os/signal.signal_recv(0x0)
        /usr/local/go/src/runtime/sigqueue.go:131 +0xa6
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.0
        /usr/local/go/src/os/signal/signal_unix.go:28 +0x41

goroutine 6 [chan receive]:
github.com/coreos/flannel/vendor/github.com/golang/glog.(*loggingT).flushDaemon(0x28a94c0)
        /go/src/github.com/coreos/flannel/vendor/github.com/golang/glog/glog.go:879 +0x9f
created by github.com/coreos/flannel/vendor/github.com/golang/glog.init.0
        /go/src/github.com/coreos/flannel/vendor/github.com/golang/glog/glog.go:410 +0x203

goroutine 34 [select, locked to thread]:
runtime.gopark(0x1ad26a0, 0x0, 0x1a58035, 0x6, 0x18, 0x1)
        /usr/local/go/src/runtime/proc.go:287 +0x12c
runtime.selectgo(0xc420469750, 0xc42025a3c0)
        /usr/local/go/src/runtime/select.go:395 +0x1149
runtime.ensureSigM.func1()
        /usr/local/go/src/runtime/signal_unix.go:511 +0x220
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2337 +0x1

goroutine 50 [select]:
main.shutdownHandler(0x7f50fe7bd1b0, 0xc4202e0280, 0xc4200ff620, 0xc420294010)
        /go/src/github.com/coreos/flannel/main.go:331 +0xf2
main.main.func1(0x7f50fe7bd1b0, 0xc4202e0280, 0xc4200ff620, 0xc420294010, 0xc420018050)
        /go/src/github.com/coreos/flannel/main.go:252 +0x49
created by main.main
        /go/src/github.com/coreos/flannel/main.go:251 +0x553

goroutine 51 [select]:
net/http.(*Transport).getConn(0xc4203ee000, 0xc42029c180, 0x0, 0xc420052000, 0x5, 0xc420162140, 0x1b, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/transport.go:948 +0x5bf
net/http.(*Transport).RoundTrip(0xc4203ee000, 0xc42018c000, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/transport.go:400 +0x6a6
github.com/coreos/flannel/vendor/github.com/coreos/etcd/client.(*simpleHTTPClient).Do.func1(0xc42008f0e0, 0xc42018c000, 0xc4203ae120)
        /go/src/github.com/coreos/flannel/vendor/github.com/coreos/etcd/client/client.go:523 +0x41
created by github.com/coreos/flannel/vendor/github.com/coreos/etcd/client.(*simpleHTTPClient).Do
        /go/src/github.com/coreos/flannel/vendor/github.com/coreos/etcd/client/client.go:522 +0x200

goroutine 52 [select]:
net.(*Resolver).LookupIPAddr(0x28a7580, 0x284d920, 0xc4203ae4e0, 0xc420162140, 0x16, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/lookup.go:196 +0x52b
net.(*Resolver).internetAddrList(0x28a7580, 0x284d920, 0xc4203ae4e0, 0x1a55550, 0x3, 0xc420162140, 0x1b, 0x0, 0x0, 0x0, ...)
        /usr/local/go/src/net/ipsock.go:293 +0x644
net.(*Resolver).resolveAddrList(0x28a7580, 0x284d920, 0xc4203ae4e0, 0x1a55bae, 0x4, 0x1a55550, 0x3, 0xc420162140, 0x1b, 0x0, ...)
        /usr/local/go/src/net/dial.go:193 +0x594
net.(*Dialer).DialContext(0xc4200ff500, 0x284d8e0, 0xc420018018, 0x1a55550, 0x3, 0xc420162140, 0x1b, 0x0, 0x0, 0x0, ...)
        /usr/local/go/src/net/dial.go:375 +0x248
net.(*Dialer).Dial(0xc4200ff500, 0x1a55550, 0x3, 0xc420162140, 0x1b, 0x1240020074360, 0x110, 0x110, 0xc42034a000)
        /usr/local/go/src/net/dial.go:320 +0x75
net.(*Dialer).Dial-fm(0x1a55550, 0x3, 0xc420162140, 0x1b, 0xc420294110, 0xc420038998, 0x404409, 0x60)
        /go/src/github.com/coreos/flannel/vendor/github.com/coreos/etcd/client/client.go:52 +0x52
net/http.(*Transport).dial(0xc4203ee000, 0x284d8e0, 0xc420018018, 0x1a55550, 0x3, 0xc420162140, 0x1b, 0x0, 0x0, 0x0, ...)
        /usr/local/go/src/net/http/transport.go:887 +0x7b
net/http.(*Transport).dialConn(0xc4203ee000, 0x284d8e0, 0xc420018018, 0x0, 0xc420052000, 0x5, 0xc420162140, 0x1b, 0xc4203ee000, 0xc42018c000, ...)
        /usr/local/go/src/net/http/transport.go:1060 +0x1d62
net/http.(*Transport).getConn.func4(0xc4203ee000, 0x284d8e0, 0xc420018018, 0xc42029c1e0, 0xc420074240)
        /usr/local/go/src/net/http/transport.go:943 +0x78
created by net/http.(*Transport).getConn
        /usr/local/go/src/net/http/transport.go:942 +0x393

goroutine 53 [select]:
net.cgoLookupIP(0x284d920, 0xc4203ae4e0, 0xc420162140, 0x16, 0xc42029c180, 0x0, 0xc420052000, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/cgo_unix.go:214 +0x1b0
net.(*Resolver).lookupIP(0x28a7580, 0x284d920, 0xc4203ae4e0, 0xc420162140, 0x16, 0x0, 0x17ebf00, 0xc4202d3a10, 0x0, 0x0)
        /usr/local/go/src/net/lookup_unix.go:95 +0x12d
net.(*Resolver).(net.lookupIP)-fm(0x284d920, 0xc4203ae4e0, 0xc420162140, 0x16, 0x0, 0x0, 0x6a1d50, 0xc4203ee000, 0x0)
        /usr/local/go/src/net/lookup.go:187 +0x56
net.glob..func10(0x284d920, 0xc4203ae4e0, 0xc420294150, 0xc420162140, 0x16, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/hook.go:19 +0x52
net.(*Resolver).LookupIPAddr.func1(0xc4203ee000, 0x284d8e0, 0xc420018018, 0x0)
        /usr/local/go/src/net/lookup.go:193 +0x5c
internal/singleflight.(*Group).doCall(0x28a7570, 0xc42015c140, 0xc420162140, 0x16, 0xc42029c300)
        /usr/local/go/src/internal/singleflight/singleflight.go:93 +0x2e
created by internal/singleflight.(*Group).DoChan
        /usr/local/go/src/internal/singleflight/singleflight.go:86 +0x31f
I0409 07:47:55.206719       1 main.go:475] Determining IP address of default interface
I0409 07:47:55.207581       1 main.go:488] Using interface with name ens32 and address 10.2.18.209
I0409 07:47:55.207625       1 main.go:505] Defaulting external address to interface address (10.2.18.209)
2018-04-09 07:47:55.209913 I | warning: ignoring ServerName for user-provided CA for backwards compatibility is deprecated
I0409 07:47:55.210056       1 main.go:235] Created subnet manager: Etcd Local Manager with Previous Subnet: None
I0409 07:47:55.210079       1 main.go:238] Installing signal handlers
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x63 pc=0x7f246f61e60b]

runtime stack:
runtime.throw(0x1a7f7cf, 0x2a)
        /usr/local/go/src/runtime/panic.go:605 +0x95
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:351 +0x2b8

goroutine 23 [syscall, locked to thread]:
runtime.cgocall(0x15273b0, 0xc42046ade8, 0x1a7d72e)
        /usr/local/go/src/runtime/cgocall.go:132 +0xe4 fp=0xc42046ada8 sp=0xc42046ad68 pc=0x402514
net._C2func_getaddrinfo(0x7f24580008c0, 0x0, 0xc4202c6690, 0xc420104030, 0x0, 0x0, 0x0)
        net/_obj/_cgo_gotypes.go:86 +0x5f fp=0xc42046ade8 sp=0xc42046ada8 pc=0x52081f
net.cgoLookupIPCNAME.func2(0x7f24580008c0, 0x0, 0xc4202c6690, 0xc420104030, 0xc42016a420, 0xc42039e020, 0x16)
        /usr/local/go/src/net/cgo_unix.go:151 +0x13f fp=0xc42046ae40 sp=0xc42046ade8 pc=0x527dbf
net.cgoLookupIPCNAME(0xc42039e020, 0x16, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/cgo_unix.go:151 +0x175 fp=0xc42046af38 sp=0xc42046ae40 pc=0x522075
net.cgoIPLookup(0xc42016a660, 0xc42039e020, 0x16)
        /usr/local/go/src/net/cgo_unix.go:203 +0x4d fp=0xc42046afc8 sp=0xc42046af38 pc=0x5227bd
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2337 +0x1 fp=0xc42046afd0 sp=0xc42046afc8 pc=0x4598f1
created by net.cgoLookupIP
        /usr/local/go/src/net/cgo_unix.go:213 +0xaf

goroutine 1 [select]:
github.com/coreos/flannel/vendor/github.com/coreos/etcd/client.(*simpleHTTPClient).Do(0xc42008f040, 0x7f2474015000, 0xc4202d8280, 0x2838420, 0xc4202c6000, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/coreos/flannel/vendor/github.com/coreos/etcd/client/client.go:531 +0x31d
github.com/coreos/flannel/vendor/github.com/coreos/etcd/client.(*redirectFollowingHTTPClient).Do(0xc42035c020, 0x7f2474015000, 0xc4202d8280, 0x2838420, 0xc4202c6000, 0x7ffe4b996ebe, 0x1b, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/coreos/flannel/vendor/github.com/coreos/etcd/client/client.go:603 +0xb2
github.com/coreos/flannel/vendor/github.com/coreos/etcd/client.(*httpClusterClient).Do(0xc4200110e0, 0x7f2474015000, 0xc4202d8280, 0x2838420, 0xc4202c6000, 0xc4205f9a88, 0xc4205f9aa8, 0x4119c8, 0x10, 0x18b1f20, ...)
        /go/src/github.com/coreos/flannel/vendor/github.com/coreos/etcd/client/client.go:360 +0x36c
github.com/coreos/flannel/vendor/github.com/coreos/etcd/client.(*httpKeysAPI).Get(0xc4203141e0, 0x7f2474015000, 0xc4202d8280, 0xc42039e000, 0x1a, 0xc420148030, 0xc42032e001, 0x3, 0x4)
        /go/src/github.com/coreos/flannel/vendor/github.com/coreos/etcd/client/keys.go:422 +0xe1
github.com/coreos/flannel/subnet/etcdv2.(*etcdSubnetRegistry).getNetworkConfig(0xc4203035f0, 0x7f2474015000, 0xc4202d8280, 0x7f2474015000, 0xc4205f9bc8, 0x410dd6, 0x7f24765dcb60)
        /go/src/github.com/coreos/flannel/subnet/etcdv2/registry.go:117 +0x125
github.com/coreos/flannel/subnet/etcdv2.(*LocalManager).GetNetworkConfig(0xc420314200, 0x7f2474015000, 0xc4202d8280, 0x453c10, 0x7f24765d5d90, 0x7f2474015005)
        /go/src/github.com/coreos/flannel/subnet/etcdv2/local_manager.go:88 +0x4b
main.getConfig(0x7f2474015000, 0xc4202d8280, 0x284ffc0, 0xc420314200, 0xc420011140, 0xc42032e000, 0xc420148020)
        /go/src/github.com/coreos/flannel/main.go:347 +0xb2
main.main()
        /go/src/github.com/coreos/flannel/main.go:262 +0x595

goroutine 5 [syscall]:
os/signal.signal_recv(0x0)
        /usr/local/go/src/runtime/sigqueue.go:131 +0xa6
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.0
        /usr/local/go/src/os/signal/signal_unix.go:28 +0x41

goroutine 6 [chan receive]:
github.com/coreos/flannel/vendor/github.com/golang/glog.(*loggingT).flushDaemon(0x28a94c0)
        /go/src/github.com/coreos/flannel/vendor/github.com/golang/glog/glog.go:879 +0x9f
created by github.com/coreos/flannel/vendor/github.com/golang/glog.init.0
        /go/src/github.com/coreos/flannel/vendor/github.com/golang/glog/glog.go:410 +0x203

goroutine 50 [select, locked to thread]:
runtime.gopark(0x1ad26a0, 0x0, 0x1a58035, 0x6, 0x18, 0x1)
        /usr/local/go/src/runtime/proc.go:287 +0x12c
runtime.selectgo(0xc420553f50, 0xc4202523c0)
        /usr/local/go/src/runtime/select.go:395 +0x1149
runtime.ensureSigM.func1()
        /usr/local/go/src/runtime/signal_unix.go:511 +0x220
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2337 +0x1

goroutine 19 [select]:
main.shutdownHandler(0x7f2474015000, 0xc4202d8280, 0xc420011140, 0xc42032e000)
        /go/src/github.com/coreos/flannel/main.go:331 +0xf2
main.main.func1(0x7f2474015000, 0xc4202d8280, 0xc420011140, 0xc42032e000, 0xc420148020)
        /go/src/github.com/coreos/flannel/main.go:252 +0x49
created by main.main
        /go/src/github.com/coreos/flannel/main.go:251 +0x553

goroutine 20 [select]:
net/http.(*Transport).getConn(0xc4203c4000, 0xc4202c6150, 0x0, 0xc420270000, 0x5, 0xc42039e020, 0x1b, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/transport.go:948 +0x5bf
net/http.(*Transport).RoundTrip(0xc4203c4000, 0xc42012a200, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/transport.go:400 +0x6a6
github.com/coreos/flannel/vendor/github.com/coreos/etcd/client.(*simpleHTTPClient).Do.func1(0xc42008f040, 0xc42012a200, 0xc42016a000)
        /go/src/github.com/coreos/flannel/vendor/github.com/coreos/etcd/client/client.go:523 +0x41
created by github.com/coreos/flannel/vendor/github.com/coreos/etcd/client.(*simpleHTTPClient).Do
        /go/src/github.com/coreos/flannel/vendor/github.com/coreos/etcd/client/client.go:522 +0x200

goroutine 21 [select]:
net.(*Resolver).LookupIPAddr(0x28a7580, 0x284d920, 0xc42016a420, 0xc42039e020, 0x16, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/lookup.go:196 +0x52b
net.(*Resolver).internetAddrList(0x28a7580, 0x284d920, 0xc42016a420, 0x1a55550, 0x3, 0xc42039e020, 0x1b, 0x0, 0x0, 0x0, ...)
        /usr/local/go/src/net/ipsock.go:293 +0x644
net.(*Resolver).resolveAddrList(0x28a7580, 0x284d920, 0xc42016a420, 0x1a55bae, 0x4, 0x1a55550, 0x3, 0xc42039e020, 0x1b, 0x0, ...)
        /usr/local/go/src/net/dial.go:193 +0x594
net.(*Dialer).DialContext(0xc420011020, 0x284d8e0, 0xc420018018, 0x1a55550, 0x3, 0xc42039e020, 0x1b, 0x0, 0x0, 0x0, ...)
        /usr/local/go/src/net/dial.go:375 +0x248
net.(*Dialer).Dial(0xc420011020, 0x1a55550, 0x3, 0xc42039e020, 0x1b, 0x1240020074360, 0x110, 0x110, 0xc4203f4240)
        /usr/local/go/src/net/dial.go:320 +0x75
net.(*Dialer).Dial-fm(0x1a55550, 0x3, 0xc42039e020, 0x1b, 0xc42032e0d0, 0xc42003d998, 0x404409, 0x60)
        /go/src/github.com/coreos/flannel/vendor/github.com/coreos/etcd/client/client.go:52 +0x52
net/http.(*Transport).dial(0xc4203c4000, 0x284d8e0, 0xc420018018, 0x1a55550, 0x3, 0xc42039e020, 0x1b, 0x0, 0x0, 0x0, ...)
        /usr/local/go/src/net/http/transport.go:887 +0x7b
net/http.(*Transport).dialConn(0xc4203c4000, 0x284d8e0, 0xc420018018, 0x0, 0xc420270000, 0x5, 0xc42039e020, 0x1b, 0xc4203c4000, 0xc42012a200, ...)
        /usr/local/go/src/net/http/transport.go:1060 +0x1d62
net/http.(*Transport).getConn.func4(0xc4203c4000, 0x284d8e0, 0xc420018018, 0xc4202c6180, 0xc420074240)
        /usr/local/go/src/net/http/transport.go:943 +0x78
created by net/http.(*Transport).getConn
        /usr/local/go/src/net/http/transport.go:942 +0x393

goroutine 22 [select]:
net.cgoLookupIP(0x284d920, 0xc42016a420, 0xc42039e020, 0x16, 0xc4202c6150, 0x0, 0xc420270000, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/cgo_unix.go:214 +0x1b0
net.(*Resolver).lookupIP(0x28a7580, 0x284d920, 0xc42016a420, 0xc42039e020, 0x16, 0x0, 0x17ebf00, 0xc420303a10, 0x0, 0x0)
        /usr/local/go/src/net/lookup_unix.go:95 +0x12d
net.(*Resolver).(net.lookupIP)-fm(0x284d920, 0xc42016a420, 0xc42039e020, 0x16, 0x0, 0x0, 0x6a1d50, 0xc4203c4000, 0x0)
        /usr/local/go/src/net/lookup.go:187 +0x56
net.glob..func10(0x284d920, 0xc42016a420, 0xc42032e110, 0xc42039e020, 0x16, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/hook.go:19 +0x52
net.(*Resolver).LookupIPAddr.func1(0xc4203c4000, 0x284d8e0, 0xc420018018, 0x0)
        /usr/local/go/src/net/lookup.go:193 +0x5c
internal/singleflight.(*Group).doCall(0x28a7570, 0xc42013e190, 0xc42039e020, 0x16, 0xc4202c6300)
        /usr/local/go/src/internal/singleflight/singleflight.go:93 +0x2e
created by internal/singleflight.(*Group).DoChan
        /usr/local/go/src/internal/singleflight/singleflight.go:86 +0x31f

**Comment by shsjshentao** [comment]
It looks like a bug of golang 1.9.2
https://github.com/golang/go/issues/22724
